name: Run python tests

on: [push, pull_request]

env:
  python-version: 3.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies with poetry
        run: poetry install --no-root

      - name: Run tests
        run: poetry run pytest -vv --strict --showlocals
